development:
    adapter: mysql
    encoding: utf8
    reconnect: false
    database: 'iamhere'
    pool: 5
    username: root
    password:
test:
    adapter: mysql
    encoding: utf8
    reconnect: false
    database: 'iamhere'
    pool: 5
    username: root
    password:
production:
    adapter: mysql
    encoding: utf8
    reconnect: false
    database: 'lionmount'
    pool: 5
