# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: admin
  admin_email: liontradecom@gmail.com
  admin_password: abcd1234
  domain_name: example.com
  secret_key_base: 9ca6f3c96836de0c11c9df8f8194800bcc4f53126d72e774e212352338b2b3ae800db94247e1e2cf55c8deeec093c21bfd9a4190f48296e513f40db65d249199

test:
  secret_key_base: 28b9842fc253fcaad5701d35d58ca3492e46de1d85b5857c2e20751cf9d36b7acd1b0b3fd65e6f2a0dee4360a13bb127078a3c1c3a0655a9f1d011634b8be191

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
